# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3.8'  # Agrega esta línea para especificar la versión del esquema de Docker Compose

services:
  web:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile  # Especifica el nombre del archivo Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - fronted
networks:
  fronted:  